const API='/api';let charts={};
const $=id=>document.getElementById(id);
async function get(url,opts){const r=await fetch(API+url,opts);if(!r.ok)throw new Error((await r.json()).detail||'Request failed');return r.json()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$(b.dataset.tab).classList.remove('hidden');if(b.dataset.tab==='dashboard')loadStats();if(b.dataset.tab==='history')loadHistory();if(b.dataset.tab==='awareness')loadAwareness()});
async function loadStats(){try{let s=await get('/dashboard/stats');$('total').textContent=s.total;$('high').textContent=s.high_risk;$('susp').textContent=s.suspicious;$('avg').textContent=s.average_score;chart('classChart','doughnut',s.classification.map(x=>x.classification),s.classification.map(x=>x.count));chart('indicatorChart','bar',s.indicators.map(x=>x.name),s.indicators.map(x=>x.count));chart('trendChart','line',s.trend.map(x=>x.date),s.trend.map(x=>x.total));}catch(e){console.error(e)}}
function chart(id,type,labels,data){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type,data:{labels,datasets:[{label:'Analyses',data}]},options:{responsive:true,plugins:{legend:{labels:{color:'#cfe0f2'}}},scales:type==='bar'||type==='line'?{x:{ticks:{color:'#8fa6bf'}},y:{ticks:{color:'#8fa6bf'}}}:{}}})}
async function analyze(){let payload={sender:$('sender').value,display_name:$('display').value,subject:$('subject').value,body:$('body').value,attachment_name:$('attachment').value,store_history:true};try{let r=await get('/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});renderResult(r)}catch(e){$('result').innerHTML='<b class="risk-high">Error:</b> '+e.message}}
function renderResult(r){let cls=r.risk_score>70?'risk-high':r.risk_score>40?'risk-mid':'risk-low';let findings=r.contributions.map(x=>`<div class="finding"><b>${x.indicator}</b> <span class="pill">+${x.points}</span><div class="muted">${x.description}</div></div>`).join('');let urls=r.urls.map(u=>`<div class="finding"><b>${escapeHtml(u.url)}</b> — ${u.score}/100<br>${u.findings.map(f=>`<span class="pill">${f[0]}</span>`).join('')}</div>`).join('')||'<span class="muted">No URLs found.</span>'; $('result').innerHTML=`<div class="result-score ${cls}">${r.risk_score}<small>/100</small></div><h3>${r.classification}</h3><p class="muted">Analysis ID: ${r.analysis_id||'not stored'}</p><h3>Why?</h3>${findings||'<p class="muted">No strong rule indicators were detected.</p>'}<h3>URL analysis</h3>${urls}<h3>Recommendations</h3><ul>${r.recommendations.map(x=>`<li>${x}</li>`).join('')}</ul>`}
function loadPhish(){$('sender').value='security-alert@account-check.invalid.test';$('display').value='Security Team';$('subject').value='URGENT: Verify Your Account Immediately';$('body').value='Your account will be suspended today. Verify your password and security code immediately. Visit http://198.51.100.10/verify-account to confirm your account.';$('attachment').value='invoice.pdf.exe'}
function loadLegit(){$('sender').value='training@example.org';$('display').value='Training Team';$('subject').value='Cybersecurity Workshop Reminder';$('body').value='Hello team, this is a reminder that the defensive cybersecurity workshop starts tomorrow at 10:00. No action is required.';$('attachment').value=''}
async function loadHistory(){let q=encodeURIComponent($('search')?.value||'');let r=await get('/analyses?q='+q);$('historyTable').innerHTML=`<table><tr><th>ID</th><th>Date</th><th>Domain</th><th>Subject</th><th>Risk</th><th>Classification</th></tr>${r.items.map(x=>`<tr><td>${x.analysis_id}</td><td>${x.created_at}</td><td>${escapeHtml(x.sender_domain)}</td><td>${escapeHtml(x.subject)}</td><td>${x.risk_score}</td><td>${x.classification}</td></tr>`).join('')}</table>`}
async function loadAwareness(){let r=await get('/awareness');$('lessons').innerHTML=r.lessons.map(x=>`<div class="lesson"><b>${x.title}</b><p class="muted">${x.text}</p></div>`).join('');$('checklist').innerHTML=r.checklist.map(x=>`<li>${x}</li>`).join('')}
function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
loadStats();
